### ISSUE TITLE
can't load iframe content

### ISSUE THREAD

**Issue by mukiwu** [Mavrin/gitbook-plugin-jsfiddle#2]
in my localhost, it work's very good, but when I push to gitbook, it only show the iframe, but no content.

![2015-03-24 6 25 03](https://cloud.githubusercontent.com/assets/3794103/6799719/1aa9b4b2-d253-11e4-9d16-7296f82facfe.png)

**Comment by Mavrin** [comment]
Can you try use https instead http in jsfiiddle url?

**Comment by mukiwu** [comment]
thanks !! it works~
