### ISSUE TITLE
JSFiddle doesn't work

### ISSUE THREAD

**Issue by revskill10** [Mavrin/gitbook-plugin-jsfiddle#3]
Hi, i use the code
[source code](https://jsfiddle.net/zalun/NmudS/embedded/result,js,html,css/)
but gitbook doesn't display embedded result.
What's wrong here?

**Comment by Mavrin** [comment]
Can you show yours markdown, where are you insert jsfidller link?

**Comment by revskill10** [comment]
Hi, i write markdown like this:

```
 [source code](https://jsfiddle.net/zalun/NmudS/embedded/result,js,html,css/)
```

**Comment by Mavrin** [comment]
You shouldn't set 'embedded/result,js,html,css' those params in url. You can just paste `[source code](http://jsfiddle.net/zalun/NmudS/)` and plugins automaticly add requires params in url.

**Comment by revskill10** [comment]
I've tried but it's the same as before. 
It's just render an anchor tag to that jsfiddle.
It's really strange here.

**Comment by Mavrin** [comment]
Can you provide gitbook config and package.json?

**Comment by Student007** [comment]
is it possible this plugin doesn't work direct at gitbook.com ? Is it only for local installation ?

**Comment by Mavrin** [comment]
Plugin work fine with gitbook. For exmaple [our book](http://api.taucharts.com/) is build direct in gitbook.com. You can see [book.json ](https://github.com/TargetProcess/taucharts-docs/blob/master/book.json) and [package.json](https://github.com/TargetProcess/taucharts-docs/blob/master/package.json). Can you show your book.json and package.json?

**Comment by IgitDanny** [comment]
Thanks, now it works. If was confusing the book configuration menu fires only errors. I copied only the example config. Adding title section and surrounding block was the solution :smile:

**Comment by Student007** [comment]
Thanks, now it works. If was confusing the book configuration menu fires only errors. I copied only the example config. Adding title section and surrounding block was the solution :smile:
