### ISSUE TITLE
New Embeds

### ISSUE THREAD

**Issue by oskarkrawczyk** [Mavrin/gitbook-plugin-jsfiddle#4]
Hey this is Oskar from JSFiddle.

Do you have any plans on updating the plugin so it can take advantage of the new embed type?

We've introduced embedding via SCRIPT a short while ago (https://medium.com/jsfiddle-updates/new-jsfiddle-embeds-93ab7a51ee11#.ts8vxtvb3), this has a few advantages over the IFRAME implementation, like the height adjusting so it always fits the height of the code.

If you have no plans on working on the plugin, I'd understand, and if you don't have any objections we'd fork your repo and refactor a few things from there.

**Comment by Mavrin** [comment]
Hi @oskarkrawczyk. Yes i have plans on updating this plugin.
But I will be see glad merge pull request in this repo if you submit it.

**Comment by oskarkrawczyk** [comment]
Cool. We're moving our docs into GitBook and wanted to use your plugin, but first it would need to comply with the new embed changes – like configuration per embed instead of global, and the aforementioned SCRIPT in favor of IFRAME.

Btw. close this issue at will as it's more of a question than an actual task/issue.

**Comment by Mavrin** [comment]
> like configuration per embed instead of global

It is possible now for width and height. You can pass params to url
https://github.com/Mavrin/gitbook-plugin-jsfiddle/blob/master/book/plugin.js#L45-L47

**Comment by Mavrin** [comment]
Will implement in 1.0.0.

**Comment by oskarkrawczyk** [comment]
Very cool!

**Comment by Mavrin** [comment]
I have almost finished new version that support new embedding. But i have one issue with it. If i have embedding with first tab result, i get ugly result, because my script calculate width and height from div in it will be reder. Example https://mavrin.gitbooks.io/test/content/README1.html. It will be great if i can pass    params width and height in script if i need it. like this `<script async src="//jsfiddle.net/taucharts/4o4z6fqn/embed/?height=300"></script>` and script inject frame with height 300 instead auto calculate. What do you think about it? @oskarkrawczyk

**Comment by oskarkrawczyk** [comment]
I see, can't you simply let the embed decide on its own about the height? 

When you embed the fiddle using `<script>` it'll just send `postMessages` back to the parent frame calculating the heights and updating it.

**Comment by oskarkrawczyk** [comment]
Disclaimer: I intentionally left the possibility to force the height out of the new embed. I just wanted the height to always be the size it needs to be.

**Comment by Mavrin** [comment]
Yes, I understand. Just i have many example,that it gets height from parent div. But i can use frame. It is ok.

**Comment by oskarkrawczyk** [comment]
Awesome, thanks for that Konstantin!

I'll be updating our docs soon, and using your plugin, there will be a honorary mention of you. I'll also be tweeting about this plugin from our jsfiddle twitter account.

**Comment by Mavrin** [comment]
You are welcome! Thank you for jsfiddle. Let me know if you have any questions.
