### ISSUE TITLE
Not rendering fiddles in gitbook example

### ISSUE THREAD

**Issue by andevsoftware** [Mavrin/gitbook-plugin-jsfiddle#6]
Hi Mavrin,

I noticed the fiddles aren't showing up in the example when the page is loaded under https (link in readme).

**Comment by Mavrin** [comment]
Hi @olivierandriessen. 

That happened, because I use http:// for jsfiddle instead https:// and browser blocks http content as unsecure.

Thank you for notice. I will fix it.

**Comment by Mavrin** [comment]
Related issue https://github.com/TargetProcess/taucharts-docs/issues/7
